package com.tikamkumar.vocabulary

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.ExpandableListviewAdapter
import com.tikamkumar.vocabulary.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

   private lateinit var binding : ActivityMainBinding
   private val title : MutableList<String> = ArrayList()
    private val subTitle : MutableList<MutableList<String>> = ArrayList()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

    val petAnimals : MutableList<String> = ArrayList()
    petAnimals.add("Dog - कुत्ता")
    petAnimals.add("Cat - बिल्ली")
    petAnimals.add("Horse - घोड़ा")
    petAnimals.add("Cow - गाय")
    petAnimals.add("Pig - सुअर")
    petAnimals.add("Goat - बकरी")
    petAnimals.add("Sheep - भेड़")
    petAnimals.add("Donkey - गधा")
    petAnimals.add("Rabbit - खरगोश")
    petAnimals.add("Rat - चूहा")
    petAnimals.add("Monkey - बंदर")
    petAnimals.add("Baboon - लंगूर")
    petAnimals.add("Camel - ऊंट")
    petAnimals.add("Buffalo - भेंस")
    petAnimals.add("Ox - बैल")

    val wildAnimal : MutableList<String> = ArrayList()
    wildAnimal.add("Lion - शेर")
    wildAnimal.add("Elephant - हाथी")
    wildAnimal.add("Tiger - बाघ")
    wildAnimal.add("Leopard - तेंदुआ(चीता)")
    wildAnimal.add("Giraffe - जिराफ़")
     wildAnimal.add("Bear - भालू")
     wildAnimal.add("Deer - हिरन")
     wildAnimal.add("Gorilla - गोरिल्ला(वनमानुष)")
     wildAnimal.add("Chimpanzee - चिंपांज़ी")
     wildAnimal.add("Fox - लोमड़ी")
     wildAnimal.add("Wolf - भेड़िया")
     wildAnimal.add("Kangaroo - कंगारू")
     wildAnimal.add("Rhinoceros - गैंडा")
     wildAnimal.add("Jackal - सियार(गीदड़)")
     wildAnimal.add("Hippopotamus - दरियाई घोड़ा")
     wildAnimal.add("Stag - बारहसिंगा")
     wildAnimal.add("Panda - पांडा")
     wildAnimal.add("Zebra - ज़ेबरा")

     val birds: MutableList<String> = ArrayList()
     birds.add("Peacock - ")
     birds.add("Pigeon - ")
     birds.add("Swan - ")
     birds.add("Swallow - ")
     birds.add("Penguin - ")
     birds.add("Parrot - ")
     birds.add("Owl - ")
     birds.add("Hen - ")
     birds.add("Crow - ")
     birds.add("Hawk - ")
     birds.add("Duck - ")
     birds.add("Dove - ")
     birds.add("Vulture - ")
     birds.add("Bat - ")
     birds.add("Crane - ")
     birds.add("Eagle - ")
     birds.add("Sparrow - ")
     birds.add("Hornbill - ")
     birds.add("Hummingbird - ")
     birds.add("Kingfisher - ")
     birds.add("Ostrich - ")
     birds.add("Robin - ")
     birds.add("Rooster - ")
     birds.add("Turkey - ")
     birds.add("Woodpecker - ")

     val fruits: MutableList<String> = ArrayList()
     fruits.add("Apple - ")
     fruits.add("Banana - ")
     fruits.add("Mango - ")
     fruits.add("Guava - ")
     fruits.add("Grapes - ")
     fruits.add("Strawberry - ")
     fruits.add("Orange - ")
     fruits.add("Papaya - ")
     fruits.add("Cherry - ")
     fruits.add("Coconut - ")
     fruits.add("Kiwi - ")
     fruits.add("Litchi - ")
     fruits.add("Peach - ")
     fruits.add("Pear - ")
     fruits.add("Pomegranate - ")
     fruits.add("Muskmelon - ")
     fruits.add("Watermelon - ")
     fruits.add("Grapefruit - ")
     fruits.add("Pine-Apple - ")
     fruits.add("Blackberry - ")
     fruits.add("Jujube - ")
     fruits.add("Custard Apple - ")
     fruits.add("Tamarind - ")

     val flowers: MutableList<String> = ArrayList()
     flowers.add("Rose")
     flowers.add("Sunflower")
     flowers.add("Daisy")
     flowers.add("Jasmine")
     flowers.add("Lotus")
     flowers.add("Lily")
     flowers.add("Dahlia")
     flowers.add("Tulip")
     flowers.add("Orchid")
     flowers.add("Amaryllis")
     flowers.add("Aster")
     flowers.add("Chrysanthemum")
     flowers.add("Daffodil")
     flowers.add("Hibiscus")
     flowers.add("Hollyhock")
     flowers.add("Iris")
     flowers.add("Magnolia")
     flowers.add("Morning-Glory")
     flowers.add("Pansy")
     flowers.add("Peony")
     flowers.add("Periwinkle")
     flowers.add("Petunia")
     flowers.add("Poppy")
     flowers.add("Tuberose")

     val colors: MutableList<String> = ArrayList()
     colors.add("Black")
     colors.add("White")
     colors.add("Red")
     colors.add("Pink")
     colors.add("Orange")
     colors.add("Yellow")
     colors.add("Blue")
     colors.add("Sky Blue")
     colors.add("Purple")
     colors.add("Green")
     colors.add("Light Green")
     colors.add("Brown")
     colors.add("Gray")
     colors.add("Golden")
     colors.add("Navy Blue")
     colors.add("Cream")
     colors.add("Silver")

     val vegetables: MutableList<String> = ArrayList()
     vegetables.add("Cucumber")
     vegetables.add("Lemon")
     vegetables.add("Tomato")
     vegetables.add("Peas")
     vegetables.add("Cabbage")
     vegetables.add("Cauliflower")
     vegetables.add("Radish")
     vegetables.add("Carrot")
     vegetables.add("Potato")
     vegetables.add("Onion")
     vegetables.add("Okra(Lady finger)")
     vegetables.add("Brinjal")
     vegetables.add("Mushroom")
     vegetables.add("Ginger")
     vegetables.add("Pumpkin")
     vegetables.add("Turnip")
     vegetables.add("Capsicum")
     vegetables.add("Spinach")
     vegetables.add("Mint")
     vegetables.add("Coriander")
     vegetables.add("Green Chilli")
     vegetables.add("Garlic")
     vegetables.add("Beet")
     vegetables.add("Bottle Gourd")
     vegetables.add("Bitter Gourd")
     vegetables.add("Fenugreek")
     vegetables.add("Sweet Potato")
     vegetables.add("Corn")

     val insects: MutableList<String> = ArrayList()
     insects.add("Ant")
     insects.add("Bee")
     insects.add("Beetle")
     insects.add("Dragonfly")
     insects.add("Butterfly")
     insects.add("Mosquito")
     insects.add("Caterpillar")
     insects.add("Centipede")
     insects.add("Cicada")
     insects.add("Cockroach")
     insects.add("fly")
     insects.add("Grasshopper")
     insects.add("Honeybee")
     insects.add("Ladybug")
     insects.add("Lizard")
     insects.add("Maggot")
     insects.add("Snail")
     insects.add("Spider")

     val seasons: ArrayList<String> = ArrayList()
     seasons.add("Spring")
     seasons.add("Summer")
     seasons.add("Autumn(Fall)")
     seasons.add("Winter")

     title.add("Pet Animals Names")
     title.add("Wild Animals Names")
     title.add("Birds Names")
     title.add("Fruits Names")
     title.add("Flowers Names")
     title.add("Colors Names")
     title.add("Vegetables Names")
     title.add("Insects Names")
     title.add("Seasons Names")

     subTitle.add(petAnimals)
     subTitle.add(wildAnimal)
     subTitle.add(birds)
     subTitle.add(fruits)
     subTitle.add(flowers)
     subTitle.add(colors)
     subTitle.add(vegetables)
     subTitle.add(insects)
     subTitle.add(seasons)

     binding.expandableListView.setAdapter(ExpandableListviewAdapter(this,title,subTitle))
    }
}